# Generated by Django 4.2.6 on 2023-10-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_usermodel_delete_user_doctor_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserCustomModel',
        ),
    ]
