# Generated by Django 4.2.6 on 2023-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_usermodel_usercustommodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='is_doctor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
