# Generated by Django 4.2.6 on 2023-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usercustommodel_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
